kind: Job
apiVersion: batch/v1
metadata: 
  name: demo-job
  namespace: nginx
spec:
  completions: 1
  parallelism: 1
  template:
    metadata:
      name: nginx-job-pod
      labels:
        app: job-pod

    spec:
      containers:
      - name: batch-container
        image: busybox
        command: ["sh","-c","echo Hello Friends! && sleep 10s"]
      restartPolicy: Never
