apiVersion: v1
kind: Pod
metadata:
  name: sidecar-demo

spec:
  containers:
    - name: main-container
      image: busybox
      command: ["sh", "-c", "while true; do echo Main Container; sleep 5; done"]

    - name: sidecar-container
      image: busybox
      command: ["sh", "-c", "while true; do echo Sidecar Container; sleep 5; done"]
